Update systemd.md to mention extra Ubuntu 22.04 command and fix binary name
Update includes mentioning that `apt install protobuf-compiler libprotobuf-dev -y` needs to be run before `cargo build --release` on Ubuntu 22.04, otherwise the user will wait a long time for it to built only to encounter the following error
```
   Compiling precompile-utils-macro v0.1.0 (/root/code/moonbeam/precompiles/utils/macro)
error: failed to run custom build command for `libp2p-core v0.37.0`

Caused by:
  process didn't exit successfully: `/root/code/moonbeam/target/release/build/libp2p-core-1e11a45529ee4184/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at '
  Could not find `protoc` installation and this build crate cannot proceed without
  this knowledge. If `protoc` is installed and this crate had trouble finding
  it, you can set the `PROTOC` environment variable with the specific path to your
  installed `protoc` binary.

  For more information: https://docs.rs/prost-build/#sourcing-protoc
  ', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.11.1/src/lib.rs:1227:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Also update includes changing the parachain and relay chain names to only include the underscore character, since horizontal dash (i.e. `-`) and braces (i.e. `(`) cause errors like the following when you run the node:
```
Dec 22 11:32:03 localhost moonbase[218583]: /opt/moonbase/start.sh: line 43: syntax error near unexpected token `('
Dec 22 11:32:03 localhost moonbase[218583]: /opt/moonbase/start.sh: line 43: `    --name "YOUR-NODE-NAME (Embedded Relay)"'
```